#!sh/bin/bash

echo "please enter your user name"

read -s USERNAME #THE VALUE ENTERD IN THE VARIABLE IS AUTOMATICALLY ATTACHED TO THE USER NAME 

echo "please enter your password"

read -s PASSWORD # THE VALE ENTERD IN THE VARIABLE IS AUTOMATICALLY ATTACHED TO THE PASSWORD

